### ISSUE TITLE
Odd issue after updating to 0.1.9

### ISSUE THREAD

**Issue by arggh** [FGM/filog#18]
After updating a working local fork to version from npm, I get this:

`TypeError: Cannot set property '/Users/arggh/Development/myapp/node_modules/filog/package.json' of undefined`

Basically, I did this (having installed a local fork of filog beforehand):

```
$ meteor npm uninstall --save filog
$ meteor npm install --save filog
$ meteor
```

Luckily, I had a brand new Macbook right next to me, so I cloned my app, installed _filog_ fresh from npm, and I get the same error when running my app.

**Comment by arggh** [comment]
Looking at the contents of tarball from [npm](https://registry.npmjs.org/filog/-/filog-0.1.9.tgz):

<img width="379" alt="filog contents" src="https://cloud.githubusercontent.com/assets/17210302/20865092/cecbca7e-ba10-11e6-978c-9dde22cc0a7e.png">

**Comment by FGM** [comment]
Looks like the published version does not contain what it should at all. You can use 0.1.9 from sources to get it working while I look into it in depth, and probably push a new version to fix this.

**Comment by FGM** [comment]
I visibly made an error in the NPM publishing process, so deprecated 0.1.9 and published 0.1.10 instead. Since this was the second incorrectly packaged version, it was an occasion to check how to avoid such problems in the future, allowing me to discover `npm pack` which implements the packaging without actually publishing. This should allow avoiding incorrect releases in the future. If you can check the new version and it works for you too, you can close the issue.

**Comment by arggh** [comment]
Hmm, after installing `filog@0.1.10` now I get this:

```
I20161204-12:10:57.027(2)? Serving logger on /logger
I20161204-12:10:57.033(2)? Processing jobs disabled.
W20161204-12:10:57.599(2)? (STDERR) /Users/arggh/.meteor/packages/meteor-tool/.1.4.2_3.1kyj8us++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161204-12:10:57.599(2)? (STDERR) 						throw(ex);
W20161204-12:10:57.599(2)? (STDERR) 						^
W20161204-12:10:57.599(2)? (STDERR) 
W20161204-12:10:57.600(2)? (STDERR) TypeError: Cannot read property 'timestamp' of undefined
W20161204-12:10:57.600(2)? (STDERR)     at MongodbSender.send (/Users/arggh/Development/myapp/node_modules/filog/lib/Senders/MongodbSender.js:67:18)
W20161204-12:10:57.600(2)? (STDERR)     at /Users/arggh/Development/myapp/node_modules/filog/lib/Logger.js:198:16
W20161204-12:10:57.600(2)? (STDERR)     at Array.forEach (native)
W20161204-12:10:57.601(2)? (STDERR)     at ServerLogger.log (/Users/arggh/Development/myapp/node_modules/filog/lib/Logger.js:197:15)
W20161204-12:10:57.601(2)? (STDERR)     at ServerLogger.debug (/Users/arggh/Development/myapp/node_modules/filog/lib/Logger.js:213
```

Are there any breaking API changes from 0.1.6?

**Comment by FGM** [comment]
0.1.9 (now 10) includes a bunch of changes, as documents in the changelog file, but they should be entirely compatible. This is strange: this "undefined" problem with the timestamp is something which was specifically included in the 0.1.9 changes because I uncovered it when writing the tests. Guess the coverage is not yet sufficient: looking into it.

**Comment by FGM** [comment]
Found it: the tests are indeed only covering the case of the valid empty context. This error happens when the context is valid but not empty, as it is when it comes from a client logger, which already includes a timestamp.

**Comment by FGM** [comment]
This is now fixed for me, test added to catch the error and prevent regressions. Attached is a candidate npm 0.1.11 release, and I've pushed a `v0.1.11` branch for the sources, to avoid creating yet another release in case this one still contains an error.
[filog-0.1.11.zip](https://github.com/FGM/filog/files/629453/filog-0.1.11.zip)

Can you confirm it is good for you too ? Also, since you contributed several error reports and a new feature with the collection reuse, do you want to be included in the contributors list in package.json ? If so, just send a PR on the v0.1.11 branch adding yourself.

**Comment by arggh** [comment]
>  to avoid creating yet another release in case this one still contains an error.
> filog-0.1.11.zip
> 
> Can you confirm it is good for you too ?

I installed FiLog from your zip file, seems to run fine in my app.

> do you want to be included in the contributors list in package.json

Sure, thank you. I'm planning on using this package for real, so I'm happy to contribute more in the future.

**Comment by FGM** [comment]
Great, then just send a PR on the v0.1.11 branch adding yourself in the "contributors" array in package.json.
